In [18]:
import seaborn as sns
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from scipy.signal import square, stft

from scipy.signal.windows import gaussian


In [126]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split

In [4]:
from DataLoader import *

In [176]:
data = DataLoader().load_ACC_data(subject='s2',event='evening')

In [178]:
data.drop(columns='UNIX_time',inplace=True)

In [204]:
data[1:2]

X_acceleration  Y_acceleration  Z_acceleration
1           -35.0           -55.0            -7.0

In [208]:
data = data.to_numpy().flatten()

In [209]:
len(data)

172800

In [182]:
len(data)/3 

19200.0

In [229]:
datas = []
for i in range(1,24):
    subject_ = f's{i}'
    data = DataLoader().load_ACC_data(subject=subject_,event='morning')
    data.drop(columns='UNIX_time',inplace=True)
    data = data.to_numpy().flatten()
    datas.append(data)

In [230]:
datas

[array([-62.,  18.,  -2., ..., -58.,  19.,  33.]),
 array([-28., -20.,  56., ..., -43., -49.,   8.]),
 array([-58.,  -6., -18., ..., -53.,   2.,  43.]),
 array([-51.,  39.,   9., ..., -37.,  -8., -52.]),
 array([-47., -16.,  45., ..., -31.,  54.,  15.]),
 array([-30., -17.,  57., ..., -38.,   1.,  54.]),
 array([-28.,  57.,  -6., ..., -61.,  17., -16.]),
 array([-50.,  16.,  43., ..., -51.,  15.,  36.]),
 array([-57., -30.,  17., ..., -57., -31.,  16.]),
 array([-11.,  22.,  59., ..., -62.,  -7., -22.]),
 array([ -2.,  60.,  21., ...,  10., -52.,  34.]),
 array([-14., -24.,  59., ..., -28.,   6., -56.]),
 array([-55.,   0.,  38., ..., -34.,  -4.,  56.]),
 array([-50., -12.,  43., ..., -46., -47.,   3.]),
 array([-30.,   0.,  58., ..., -66.,  -1.,   6.]),
 array([-16.,  -1.,  62., ..., -25., -54.,  -4.]),
 array([-33.,   0.,  57., ..., -20.,   1.,  62.]),
 array([-57.,  -2.,  34., ..., -31.,   0.,  58.]),
 array([-59.,  11.,  28., ..., -41.,  23.,  44.]),
 array([  0.,  18.,  61., ..., 

In [231]:
datas = pd.DataFrame(datas)

In [232]:
datas.shape

(23, 172800)

In [40]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler 

In [41]:
from sklearn.pipeline import make_pipeline

In [43]:
num_transformer=make_pipeline(StandardScaler())

In [49]:
num_transformer.fit(acc_s1m)

Pipeline(steps=[('standardscaler', StandardScaler())])

In [51]:
acc_s1m=num_transformer.transform(acc_s1m)

In [54]:
pd.DataFrame(acc_s1m)

0         1         2
0     -0.743233 -0.771796  0.160711
1     -0.874754 -0.629046  0.004586
2     -0.874754 -0.533879 -0.073476
3     -0.874754 -0.438712 -0.112508
4     -0.808993 -0.438712 -0.190570
...         ...       ...       ...
57595 -0.940514 -0.248379 -0.854102
57596 -0.940514 -0.248379 -0.854102
57597 -0.940514 -0.248379 -0.893133
57598 -0.940514 -0.248379 -0.932164
57599 -0.940514 -0.248379 -0.932164

[57600 rows x 3 columns]

In [233]:
def normalization(subject):
    num_transformer=make_pipeline(StandardScaler())
    num_transformer.fit(subject)
    return pd.DataFrame(num_transformer.transform(subject),columns=subject.columns)

In [234]:
df=normalization(datas)

In [235]:
df.shape

(23, 172800)

In [236]:
X = df

In [220]:
info = pd.read_excel('data/general_info.xlsx')

In [221]:
info

subjects  age  gender         education employment marital status smoking  \
0        S1   27    male  associate degree       full         single      no   
1        S2   33  female  associate degree       full        married      no   
2        S3   23    male       high school       full         single     yes   
3        S4   25    male  associate degree       full         single      no   
4        S5   29    male       high school       full         single      no   
5        S6   28    male  associate degree       full         single      no   
6        S7   27    male       high school       full        married      no   
7        S8   19    male       high school       full         single      no   
8        S9   31  female   graduate degree       full        married      no   
9       S10   25    male       high school       full         single     yes   
10      S11   24  female   graduate degree       full         single      no   
11      S12   31  female     master degree       full        married      no   
12      S13   24  female   graduate degree       full         single      no   
13      S14   32  female     master degree       full         single     yes   
14      S15   37  female               phd       full         single      no   
15      S16   24  female   graduate degree       full         single      no   
16      S17   40    male     master degree       full         single     yes   
17      S18   30  female     master degree       full        married      no   
18      S19   25  female   graduate degree       full         single      no   
19      S20   49  female    primary-school       full        married     yes   
20      S21   33    male   graduate degree       full        married     yes   
21      S22   28  female     master degree       full         single      no   
22      S23   30  female   graduate degree       full         single      no   

   sleep status       salary chronic disease drug status gym status  \
0            no  10000-15000              no          no        yes   
1           yes  10000-15000              no          no         no   
2            no   5000-10000              no          no         no   
3            no   5000-10000              no          no        yes   
4           yes   5000-10000              no          no        yes   
5           yes   5000-10000              no          no         no   
6           yes  10000-15000              no          no        yes   
7            no   5000-10000              no          no         no   
8            no  15000-20000              no          no         no   
9           yes  10000-20000              no          no        yes   
10          yes  15000-20000              no          no        yes   
11          yes  15000-20000              no         yes        yes   
12           no  15000-20000              no         yes         no   
13           no  15000-20000             yes          no         no   
14           no  15000-20000              no          no         no   
15          yes  15000-20000              no          no         no   
16           no  15000-20000              no          no        yes   
17           no  15000-20000              no         yes         no   
18           no  15000-20000              no          no        yes   
19           no   5000-10000             yes         yes         no   
20           no  30000-40000              no          no         no   
21          yes  15000-20000              no          no         no   
22           no  15000-20000              no          no         no   

    duration of employment  last sleep time  morning-mental fatigue state  \
0                        9                5                            11   
1                        9                8                            18   
2                        9                4                             0   
3                        9                7                          

In [222]:
y = info[['morning-mental fatigue state']]

In [223]:
y

morning-mental fatigue state
0                             11
1                             18
2                              0
3                             12
4                             10
5                             11
6                              5
7                             11
8                              2
9                              5
10                             9
11                             9
12                            17
13                             4
14                             2
15                            12
16                            12
17                            19
18                            13
19                             7
20                            11
21                             3
22                             5

In [246]:
from sklearn.neural_network import MLPClassifier

ImportError: cannot import name 'MLPRegression' from 'sklearn.neural_network' (/Users/jingyang/.pyenv/versions/3.10.6/envs/walkies/lib/python3.10/site-packages/sklearn/neural_network/__init__.py)

In [239]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.3,
                                                    random_state = 42)

In [225]:
pipe = make_pipeline(MLPClassifier())

In [238]:
X.shape

(23, 172800)

In [227]:
y.shape

(23, 1)

In [240]:
pipe.fit(X_train,y_train)

/Users/jingyang/.pyenv/versions/3.10.6/envs/walkies/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('mlpclassifier', MLPClassifier())])

0         1.097810
1        -0.225674
2         1.140632
3         1.039388
4        -0.214274
            ...   
172795   -1.936905
172796   -0.526307
172797    0.976430
172798   -1.846246
172799   -0.524094
Name: 15, Length: 172800, dtype: float64

In [245]:
pipe.predict(X_test)

array([ 2,  2, 11,  2,  2,  2,  2])