In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('../')

# Imports

In [20]:
import numpy as np
import os
import pandas as pd
import sys
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
###  Models
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import ElasticNet
from sklearn.pipeline import make_pipeline
### Classes
from src.DataLoader import DataLoader
from src.Tensor import *
### Others imports
from scipy.stats import entropy
from scipy.stats import entropy, kurtosis, skew

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report,recall_score, precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

# Datas 

In [3]:
df_subjects_list = Tensor_data()
df_subjects_list

[       X_acceleration  Y_acceleration  Z_acceleration
 0               -62.0            18.0            -2.0
 1               -63.0            18.0            -2.0
 2               -61.0            15.0            -4.0
 3               -62.0            15.0            -8.0
 4               -64.0            14.0            -9.0
 ...               ...             ...             ...
 57595           -56.0            20.0            29.0
 57596           -53.0            19.0            30.0
 57597           -58.0            22.0            33.0
 57598           -56.0            20.0            31.0
 57599           -58.0            19.0            33.0
 
 [57600 rows x 3 columns],
        X_acceleration  Y_acceleration  Z_acceleration
 0               -63.0           -15.0            25.0
 1               -65.0           -12.0            21.0
 2               -65.0           -10.0            19.0
 3               -65.0            -8.0            18.0
 4               -64.0            -8

In [4]:
Xlist_normalized = normalize_list_data(df_subjects_list)
Xlist_normalized

[       X_acceleration  Y_acceleration  Z_acceleration
 0           -0.589457       -0.114222       -0.212423
 1           -0.671152       -0.114222       -0.212423
 2           -0.507761       -0.269832       -0.308387
 3           -0.589457       -0.269832       -0.500315
 4           -0.752848       -0.321702       -0.548297
 ...               ...             ...             ...
 57595       -0.099284       -0.010482        1.275020
 57596        0.145802       -0.062352        1.323002
 57597       -0.262675        0.093258        1.466948
 57598       -0.099284       -0.010482        1.370984
 57599       -0.262675       -0.062352        1.466948
 
 [57600 rows x 3 columns],
        X_acceleration  Y_acceleration  Z_acceleration
 0           -0.743233       -0.771796        0.160711
 1           -0.874754       -0.629046        0.004586
 2           -0.874754       -0.533879       -0.073476
 3           -0.874754       -0.438712       -0.112508
 4           -0.808993       -0.4387

In [5]:
Y_label = label_creator()
Y_label

fatigue  is_tired
0        11         0
1        18         1
2         0         0
3        12         1
4        10         0
5        11         0
6         5         0
7        11         0
8         2         0
9         5         0
10        9         0
11        9         0
12       17         1
13        4         0
14        2         0
15       12         1
16       12         1
17       19         1
18       13         1
19        7         0
20       11         0
21        3         0
22        5         0
23       14         1
24       14         1
25       14         1
26       12         1
27       13         1
28       11         0
29        1         0
30       11         0
31       13         1
32       11         0
33        8         0
34       19         1
35       21         1
36       22         1
37       16         1
38       15         1
39       12         1
40       26         1
41        4         0
42       19         1
43       21         1
44       18         1
45       20         1

In [6]:
def magnitude_acceleration(d):
    return np.sqrt(d[0]**2+d[1]**2+d[2]**2)

In [7]:
for elm in Xlist_normalized:
    elm['mag_acc'] = elm.apply(magnitude_acceleration, axis = 1)

/tmp/ipykernel_7709/2729946542.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return np.sqrt(d[0]**2+d[1]**2+d[2]**2)
/tmp/ipykernel_7709/2729946542.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return np.sqrt(d[0]**2+d[1]**2+d[2]**2)
/tmp/ipykernel_7709/2729946542.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return np.sqrt(d[0]**2+d[1]**2+d[2]**2)
/tmp/ipykernel_7709/2729946542.py:2: FutureWarning: Series.__getite

In [46]:
Xlist_normalized[0].shape

(57600, 4)

In [47]:
Xlist_normalized[0][['mag_acc']].iloc[9600:].shape

(48000, 1)

In [50]:
57600 - 9600

48000

In [59]:
48000*46

2208000

In [55]:
57600/5

11520.0

In [51]:
### at the end => Should have : shape = (46,9600*46)

In [54]:
9600*46

441600

In [80]:
acc_magn_list = []
for elements in Xlist_normalized:
    acc_magn_list.append(elements[['mag_acc']].iloc[48000:])
acc_magn_list

[        mag_acc
 48000  1.354892
 48001  2.605170
 48002  3.477979
 48003  2.732009
 48004  3.009978
 ...         ...
 57595  1.278923
 57596  1.332472
 57597  1.493195
 57598  1.374614
 57599  1.491584
 
 [9600 rows x 1 columns],
         mag_acc
 48000  1.804213
 48001  3.005738
 48002  1.664252
 48003  2.547105
 48004  2.289032
 ...         ...
 57595  1.294507
 57596  1.294507
 57597  1.320585
 57598  1.347289
 57599  1.347289
 
 [9600 rows x 1 columns],
         mag_acc
 48000  1.704063
 48001  1.844403
 48002  1.759947
 48003  1.636535
 48004  1.685826
 ...         ...
 57595  2.508832
 57596  2.431972
 57597  2.334966
 57598  2.161201
 57599  2.077737
 
 [9600 rows x 1 columns],
         mag_acc
 48000  0.915992
 48001  0.915992
 48002  0.922597
 48003  0.919450
 48004  0.918100
 ...         ...
 57595  1.490152
 57596  1.434914
 57597  1.303662
 57598  1.479825
 57599  1.114110
 
 [9600 rows x 1 columns],
         mag_acc
 48000  2.147409
 48001  1.943396
 48002  1.723555
 480

In [81]:
acc_magn_list[0].shape

(9600, 1)

In [82]:
len(acc_magn_list)

46

In [83]:
acc_magn_list

[        mag_acc
 48000  1.354892
 48001  2.605170
 48002  3.477979
 48003  2.732009
 48004  3.009978
 ...         ...
 57595  1.278923
 57596  1.332472
 57597  1.493195
 57598  1.374614
 57599  1.491584
 
 [9600 rows x 1 columns],
         mag_acc
 48000  1.804213
 48001  3.005738
 48002  1.664252
 48003  2.547105
 48004  2.289032
 ...         ...
 57595  1.294507
 57596  1.294507
 57597  1.320585
 57598  1.347289
 57599  1.347289
 
 [9600 rows x 1 columns],
         mag_acc
 48000  1.704063
 48001  1.844403
 48002  1.759947
 48003  1.636535
 48004  1.685826
 ...         ...
 57595  2.508832
 57596  2.431972
 57597  2.334966
 57598  2.161201
 57599  2.077737
 
 [9600 rows x 1 columns],
         mag_acc
 48000  0.915992
 48001  0.915992
 48002  0.922597
 48003  0.919450
 48004  0.918100
 ...         ...
 57595  1.490152
 57596  1.434914
 57597  1.303662
 57598  1.479825
 57599  1.114110
 
 [9600 rows x 1 columns],
         mag_acc
 48000  2.147409
 48001  1.943396
 48002  1.723555
 480

In [84]:
table_X = acc_magn_list[0].T
table_X.shape

(1, 9600)

In [85]:
acc_magn_list

len(acc_magn_list)
table_X = acc_magn_list[0].T
for i in range(1,46):
    table_X = pd.concat([table_X,acc_magn_list[i].T], axis = 0)

In [89]:
table_X

48000     48001     48002     48003     48004     48005     48006  \
mag_acc  1.354892  2.605170  3.477979  2.732009  3.009978  3.360394  1.486641   
mag_acc  1.804213  3.005738  1.664252  2.547105  2.289032  2.187739  1.960148   
mag_acc  1.704063  1.844403  1.759947  1.636535  1.685826  1.769907  1.692458   
mag_acc  0.915992  0.915992  0.922597  0.919450  0.918100  0.918100  0.914937   
mag_acc  2.147409  1.943396  1.723555  1.814874  1.746836  1.797781  1.844017   
mag_acc  0.437734  1.570256  1.621249  1.737714  1.374948  1.241095  1.568051   
mag_acc  0.884824  0.927288  1.019651  0.998808  0.982374  0.846204  0.882133   
mag_acc  1.244272  1.924043  3.053072  2.640506  2.253559  2.369584  2.553450   
mag_acc  2.171215  2.195744  2.300123  2.217395  2.214482  2.258275  2.214482   
mag_acc  0.520517  0.538926  0.555865  0.590762  0.590762  0.590762  0.538926   
mag_acc  0.918329  0.870390  0.899397  0.894329  0.894329  0.906385  0.894329   
mag_acc  2.120033  2.044332  2.078869  2.127979  2.095343  2.129885  2.161403   
mag_acc  1.377546  1.377546  1.352359  1.358521  1.358521  1.377546  1.377546   
mag_acc  3.419670  3.213186  3.122657  3.066694  3.037466  2.901748  2.776675   
mag_acc  1.386698  1.435310  1.291616  1.119892  1.021989  0.954193  0.925233   
mag_acc  2.125810  2.040796  1.926058  1.809455  1.870990  1.906951  1.868550   
mag_acc  1.425296  1.372209  2.177096  2.389422  3.090238  2.823378  3.163268   
mag_acc  1.528802  1.547763  1.596837  1.628457  1.616038  1.616038  1.616038   
mag_acc  0.894004  0.894004  0.887063  0.807523  0.793354  0.768405  0.815193   
mag_acc  0.909538  0.873687  0.932392  0.792819  0.815117  0.840542  0.890204   
mag_acc  1.304452  1.153789  1.147280  1.488927  1.537116  1.683991  1.673187   
mag_acc  0.688535  0.627714  0.661990  0.672615  0.672615  0.672615  0.672615   
mag_acc  2.001930  2.001930  2.001930  2.001930  1.984324  1.984324  2.001930   
mag_acc  1.284280  1.273899  1.273899  1.284280  1.273899  1.273899  1.273899   
mag_acc  2.661186  2.383135  2.598028  3.284996  2.766465  2.971351  2.754802   
mag_acc  0.750033  0.768036  0.734836  0.701308  0.788368  0.690216  0.666898   
mag_acc  1.520907  1.551289  1.520907  1.520907  1.520907  1.520907  1.551289   
mag_acc  0.778480  0.863508  0.919690  0.965550  0.954030  1.015290  0.963544   
mag_acc  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944   
mag_acc  1.529262  1.547122  1.568877  1.591411  1.568877  1.552372  1.568877   
mag_acc  1.904717  1.871858  1.871858  1.839539  1.845357  1.845357  1.871858   
mag_acc  1.520961  1.362220  1.430612  1.478511  1.455988  1.441203  1.441203   
mag_acc  3.015183  2.951704  2.888860  2.911050  2.892518  2.910446  2.951704   
mag_acc  1.055615  1.033073  1.033073  1.021971  1.047819  1.021971  1.021971   
mag_acc  2.381913  2.358673  2.379315  2.358673  2.379315  2.379315  2.381913   
mag_acc  0.895302  0.903697  0.942900  0.934857  0.895302  0.895302  0.895302   
mag_acc  2.390954  2.017224  1.736176  1.672327  1.181146  1.236225  1.092264   
mag_acc  0.761300  0.761300  0.761300  0.807062  0.761300  0.765059  0.765059   
mag_acc  1.937858  1.946522  1.946522  1.946522  1.946522  1.946522  1.937858   
mag_acc  0.948512  0.875140  0.936592  0.367916  0.948512  0.875140  1.005491   
mag_acc  0.804942  0.828584  0.804942  0.828584  0.828584  0.828584  0.828584   
mag_acc  0.941912  0.719157  0.719157  0.938535  0.639418  0.430687  0.352318   
mag_acc  1.312264  1.312264  1.260405  1.228788  1.505282  1.293226  1.426830   
mag_acc  1.691393  1.668923  1.668923  1.668923  1.695943  1.679781  1.679781   
mag_acc  1.139136  1.156529  1.156529  1.156529  1.139136  1.139136  1.124012   
mag_acc  1.315726  1.347726  1.347726  1.359755  1.529940  1.567020  1.516523   

            48007     48008     48009  ...     57590     57591     57592  \
mag_acc  1.883873  2.068234  2.737113  ...  1.196505  1.444397  1.039913   
mag_acc  1.626767  2.307444  2.516623  ...  1.170498

In [67]:
# ### New function for concatenation :
# list_acc_transpose = []
# for i in range(1,46):
#     list_acc_transpose.append(acc_magn_list[i].T)


In [90]:
# acc_magn_list[0].T

In [91]:
# acc_magn_list[1].T.shape

In [92]:
# table_X.shape

In [79]:
# last_5 = 57599 - 9600
last_5 = 48000  # .iloc[48000:]  => .iloc[last_5:]
# at the end, we should have : 9600*46

In [93]:
X_table_5min = table_X
X_table_5min.index = [f'S_{i}' for i in range(1,47)]
X_table_5min

48000     48001     48002     48003     48004     48005     48006  \
S_1   1.354892  2.605170  3.477979  2.732009  3.009978  3.360394  1.486641   
S_2   1.804213  3.005738  1.664252  2.547105  2.289032  2.187739  1.960148   
S_3   1.704063  1.844403  1.759947  1.636535  1.685826  1.769907  1.692458   
S_4   0.915992  0.915992  0.922597  0.919450  0.918100  0.918100  0.914937   
S_5   2.147409  1.943396  1.723555  1.814874  1.746836  1.797781  1.844017   
S_6   0.437734  1.570256  1.621249  1.737714  1.374948  1.241095  1.568051   
S_7   0.884824  0.927288  1.019651  0.998808  0.982374  0.846204  0.882133   
S_8   1.244272  1.924043  3.053072  2.640506  2.253559  2.369584  2.553450   
S_9   2.171215  2.195744  2.300123  2.217395  2.214482  2.258275  2.214482   
S_10  0.520517  0.538926  0.555865  0.590762  0.590762  0.590762  0.538926   
S_11  0.918329  0.870390  0.899397  0.894329  0.894329  0.906385  0.894329   
S_12  2.120033  2.044332  2.078869  2.127979  2.095343  2.129885  2.161403   
S_13  1.377546  1.377546  1.352359  1.358521  1.358521  1.377546  1.377546   
S_14  3.419670  3.213186  3.122657  3.066694  3.037466  2.901748  2.776675   
S_15  1.386698  1.435310  1.291616  1.119892  1.021989  0.954193  0.925233   
S_16  2.125810  2.040796  1.926058  1.809455  1.870990  1.906951  1.868550   
S_17  1.425296  1.372209  2.177096  2.389422  3.090238  2.823378  3.163268   
S_18  1.528802  1.547763  1.596837  1.628457  1.616038  1.616038  1.616038   
S_19  0.894004  0.894004  0.887063  0.807523  0.793354  0.768405  0.815193   
S_20  0.909538  0.873687  0.932392  0.792819  0.815117  0.840542  0.890204   
S_21  1.304452  1.153789  1.147280  1.488927  1.537116  1.683991  1.673187   
S_22  0.688535  0.627714  0.661990  0.672615  0.672615  0.672615  0.672615   
S_23  2.001930  2.001930  2.001930  2.001930  1.984324  1.984324  2.001930   
S_24  1.284280  1.273899  1.273899  1.284280  1.273899  1.273899  1.273899   
S_25  2.661186  2.383135  2.598028  3.284996  2.766465  2.971351  2.754802   
S_26  0.750033  0.768036  0.734836  0.701308  0.788368  0.690216  0.666898   
S_27  1.520907  1.551289  1.520907  1.520907  1.520907  1.520907  1.551289   
S_28  0.778480  0.863508  0.919690  0.965550  0.954030  1.015290  0.963544   
S_29  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944   
S_30  1.529262  1.547122  1.568877  1.591411  1.568877  1.552372  1.568877   
S_31  1.904717  1.871858  1.871858  1.839539  1.845357  1.845357  1.871858   
S_32  1.520961  1.362220  1.430612  1.478511  1.455988  1.441203  1.441203   
S_33  3.015183  2.951704  2.888860  2.911050  2.892518  2.910446  2.951704   
S_34  1.055615  1.033073  1.033073  1.021971  1.047819  1.021971  1.021971   
S_35  2.381913  2.358673  2.379315  2.358673  2.379315  2.379315  2.381913   
S_36  0.895302  0.903697  0.942900  0.934857  0.895302  0.895302  0.895302   
S_37  2.390954  2.017224  1.736176  1.672327  1.181146  1.236225  1.092264   
S_38  0.761300  0.761300  0.761300  0.807062  0.761300  0.765059  0.765059   
S_39  1.937858  1.946522  1.946522  1.946522  1.946522  1.946522  1.937858   
S_40  0.948512  0.875140  0.936592  0.367916  0.948512  0.875140  1.005491   
S_41  0.804942  0.828584  0.804942  0.828584  0.828584  0.828584  0.828584   
S_42  0.941912  0.719157  0.719157  0.938535  0.639418  0.430687  0.352318   
S_43  1.312264  1.312264  1.260405  1.228788  1.505282  1.293226  1.426830   
S_44  1.691393  1.668923  1.668923  1.668923  1.695943  1.679781  1.679781   
S_45  1.139136  1.156529  1.156529  1.156529  1.139136  1.139136  1.124012   
S_46  1.315726  1.347726  1.347726  1.359755  1.529940  1.567020  1.516523   

         48007     48008     48009  ...     57590     57591     57592  \
S_1   1.883873  2.068234  2.737113  ...  1.196505  1.444397  1.039913   
S_2   1.626767  2.307444  2.516623  ...  1.170498  1.230992  1.304768   
S_3   1.909588  1.864238  1.295559  ...  2.546858  3.810395  2.661874   
S_4   0.918100  0.974562  0.974562  ...  1.193225 

In [94]:
X_table_5min  #0, 1/32, 2/32, 3/32 ...

48000     48001     48002     48003     48004     48005     48006  \
S_1   1.354892  2.605170  3.477979  2.732009  3.009978  3.360394  1.486641   
S_2   1.804213  3.005738  1.664252  2.547105  2.289032  2.187739  1.960148   
S_3   1.704063  1.844403  1.759947  1.636535  1.685826  1.769907  1.692458   
S_4   0.915992  0.915992  0.922597  0.919450  0.918100  0.918100  0.914937   
S_5   2.147409  1.943396  1.723555  1.814874  1.746836  1.797781  1.844017   
S_6   0.437734  1.570256  1.621249  1.737714  1.374948  1.241095  1.568051   
S_7   0.884824  0.927288  1.019651  0.998808  0.982374  0.846204  0.882133   
S_8   1.244272  1.924043  3.053072  2.640506  2.253559  2.369584  2.553450   
S_9   2.171215  2.195744  2.300123  2.217395  2.214482  2.258275  2.214482   
S_10  0.520517  0.538926  0.555865  0.590762  0.590762  0.590762  0.538926   
S_11  0.918329  0.870390  0.899397  0.894329  0.894329  0.906385  0.894329   
S_12  2.120033  2.044332  2.078869  2.127979  2.095343  2.129885  2.161403   
S_13  1.377546  1.377546  1.352359  1.358521  1.358521  1.377546  1.377546   
S_14  3.419670  3.213186  3.122657  3.066694  3.037466  2.901748  2.776675   
S_15  1.386698  1.435310  1.291616  1.119892  1.021989  0.954193  0.925233   
S_16  2.125810  2.040796  1.926058  1.809455  1.870990  1.906951  1.868550   
S_17  1.425296  1.372209  2.177096  2.389422  3.090238  2.823378  3.163268   
S_18  1.528802  1.547763  1.596837  1.628457  1.616038  1.616038  1.616038   
S_19  0.894004  0.894004  0.887063  0.807523  0.793354  0.768405  0.815193   
S_20  0.909538  0.873687  0.932392  0.792819  0.815117  0.840542  0.890204   
S_21  1.304452  1.153789  1.147280  1.488927  1.537116  1.683991  1.673187   
S_22  0.688535  0.627714  0.661990  0.672615  0.672615  0.672615  0.672615   
S_23  2.001930  2.001930  2.001930  2.001930  1.984324  1.984324  2.001930   
S_24  1.284280  1.273899  1.273899  1.284280  1.273899  1.273899  1.273899   
S_25  2.661186  2.383135  2.598028  3.284996  2.766465  2.971351  2.754802   
S_26  0.750033  0.768036  0.734836  0.701308  0.788368  0.690216  0.666898   
S_27  1.520907  1.551289  1.520907  1.520907  1.520907  1.520907  1.551289   
S_28  0.778480  0.863508  0.919690  0.965550  0.954030  1.015290  0.963544   
S_29  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944  0.985944   
S_30  1.529262  1.547122  1.568877  1.591411  1.568877  1.552372  1.568877   
S_31  1.904717  1.871858  1.871858  1.839539  1.845357  1.845357  1.871858   
S_32  1.520961  1.362220  1.430612  1.478511  1.455988  1.441203  1.441203   
S_33  3.015183  2.951704  2.888860  2.911050  2.892518  2.910446  2.951704   
S_34  1.055615  1.033073  1.033073  1.021971  1.047819  1.021971  1.021971   
S_35  2.381913  2.358673  2.379315  2.358673  2.379315  2.379315  2.381913   
S_36  0.895302  0.903697  0.942900  0.934857  0.895302  0.895302  0.895302   
S_37  2.390954  2.017224  1.736176  1.672327  1.181146  1.236225  1.092264   
S_38  0.761300  0.761300  0.761300  0.807062  0.761300  0.765059  0.765059   
S_39  1.937858  1.946522  1.946522  1.946522  1.946522  1.946522  1.937858   
S_40  0.948512  0.875140  0.936592  0.367916  0.948512  0.875140  1.005491   
S_41  0.804942  0.828584  0.804942  0.828584  0.828584  0.828584  0.828584   
S_42  0.941912  0.719157  0.719157  0.938535  0.639418  0.430687  0.352318   
S_43  1.312264  1.312264  1.260405  1.228788  1.505282  1.293226  1.426830   
S_44  1.691393  1.668923  1.668923  1.668923  1.695943  1.679781  1.679781   
S_45  1.139136  1.156529  1.156529  1.156529  1.139136  1.139136  1.124012   
S_46  1.315726  1.347726  1.347726  1.359755  1.529940  1.567020  1.516523   

         48007     48008     48009  ...     57590     57591     57592  \
S_1   1.883873  2.068234  2.737113  ...  1.196505  1.444397  1.039913   
S_2   1.626767  2.307444  2.516623  ...  1.170498  1.230992  1.304768   
S_3   1.909588  1.864238  1.295559  ...  2.546858  3.810395  2.661874   
S_4   0.918100  0.974562  0.974562  ...  1.193225 

In [11]:
32 * 60 *5  #32 sample rate : frequence d'echantillonnage  freq = 1/T  unt = 1/64g ===> 5 mins tail walk


# 4 => 4/64  * g => 32hz = > 32 echantillonage en

9600

In [61]:
9600*46

441600

(46, 48000)

In [15]:
# (48000/46)/(32*60)


0.5434782608695652

In [72]:
X_norm_5min = normalize_data(X_table_5min)
X_norm_5min.head()

9600      9601      9602      9603      9604      9605      9606   \
0 -0.157134 -0.065356 -0.070492 -0.006548  0.012594 -0.081851 -0.041588   
1 -0.738496 -0.713245 -0.723520 -0.690195 -0.783274 -0.836168 -0.773961   
2  0.296905  0.638214  0.118767 -0.461577  0.790571  1.069376 -1.227761   
3 -0.588533 -0.456238 -0.645936 -1.029077 -0.369918 -0.507810 -0.694476   
4 -0.128560 -0.155427 -0.101605 -0.148694 -0.230397 -0.252839 -0.146997   

      9607      9608      9609   ...     57590     57591     57592     57593  \
0  0.016089  0.011689  0.274524  ... -0.654219 -0.425139 -0.773544 -0.576305   
1 -0.766592 -0.746393 -0.766225  ... -0.677334 -0.612061 -0.535643 -0.539300   
2 -0.585525 -0.994237 -0.429921  ...  0.545997  1.647245  0.683355  0.277320   
3 -0.677648 -0.625529 -0.441510  ... -0.657134 -0.727100 -0.901444 -0.836321   
4 -0.189460 -0.195878 -0.198598  ... -0.851440 -0.831822 -0.810672 -0.803341   

      57594     57595     57596     57597     57598     57599  
0 -0.570074 -0.587348 -0.528472 -0.382458 -0.482877 -0.348351  
1 -0.546729 -0.573676 -0.562178 -0.533818 -0.506963 -0.474406  
2  0.398231  0.491637  0.447707  0.355680  0.210468  0.163711  
3 -0.676848 -0.402039 -0.437519 -0.548657 -0.390138 -0.678110  
4 -1.028024 -0.890255 -0.767013 -0.839133 -0.883432 -0.796263  

[5 rows x 48000 columns]

In [60]:
X_norm_5min.shape

(46, 48000)

In [16]:
# Y_label
Y_label_binary = Y_label.iloc[:,1]
Y_label_binary  ### 46 elements

0     0
1     1
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    1
13    0
14    0
15    1
16    1
17    1
18    1
19    0
20    0
21    0
22    0
23    1
24    1
25    1
26    1
27    1
28    0
29    0
30    0
31    1
32    0
33    0
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    0
42    1
43    1
44    1
45    1
Name: is_tired, dtype: int64

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X_table_5min, Y_label_binary, test_size=0.3)

In [117]:
'MLP Classifier'
X_train_MLP = X_train
y_train_MLP = y_train
X_test_MLP = X_test
y_test_MLP = y_test
model_MLP = MLPClassifier()
pipe = make_pipeline(model_MLP)
pipe.fit(X_train_MLP, y_train_MLP)
y_pred_MLP = pipe.predict(X_test_MLP)
print(y_pred_MLP)

recall = recall_score(y_test_MLP, y_pred_MLP)
accuracy = accuracy_score(y_test_MLP, y_pred_MLP)
precision = precision_score(y_test_MLP, y_pred_MLP)

[1 1 1 0 0 0 1 0 0 0 0 1 1 0]


In [118]:
display(recall)
display(accuracy)
display(precision)

0.375

0.42857142857142855

0.5

In [99]:
def test_classifiers(X_train, y_train, X_test, y_test):
    models = {
        'MLP Classifier': MLPClassifier(),  ## --> This is your baseline = chance
        'Logistic Regression': LogisticRegression(),
        'Decision Tree': DecisionTreeClassifier(),
        'Random Forest': RandomForestClassifier(),
        'Gradient Boosting': GradientBoostingClassifier(),
        'K-Nearest Neighbors': KNeighborsClassifier()

    }

    results = {}
    X_model = X_train
    y_model = y_train
    X_test_model = X_test
    y_test_model = y_test
    for name, model in models.items():
        pipe = make_pipeline(model)
        pipe.fit(X_model, y_model)
        y_pred = pipe.predict(X_test_model)
        print(y_pred)

        recall = recall_score(y_test_model, y_pred)
        accuracy = accuracy_score(y_test_model, y_pred)
        precision = precision_score(y_test_model, y_pred)

        report = classification_report(y_test_model, y_pred)

        results[name] = {
            'accuracy': accuracy,
            'report': report,
            'precision' : precision
        }

        print(f"{name}:\n")
        print(f"Recall: {recall}\n")
        print(f"Precision: {precision}\n")
        print(f"Accuracy: {accuracy}\n")
        # table_results = pd.DataFrame({"Recall": recall,"Precision": precision, "Accuracy": accuracy})
        # print(f"Classification Report:\n{report}\n")
        # print(table_results)

    return results

In [100]:
resultats = test_classifiers(X_train, y_train, X_test, y_test)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
MLP Classifier:

Recall: 1.0

Precision: 0.7857142857142857

Accuracy: 0.7857142857142857

[0 0 0 1 0 0 1 0 0 0 0 0 1 0]
Logistic Regression:

Recall: 0.18181818181818182

Precision: 0.6666666666666666

Accuracy: 0.2857142857142857



/home/marie/.pyenv/versions/3.10.6/envs/walkies/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/marie/.pyenv/versions/3.10.6/envs/walkies/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/marie/.pyenv/versions/3.10.6/envs/walkies/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

[0 0 0 0 0 0 0 0 0 1 1 0 0 0]
Decision Tree:

Recall: 0.18181818181818182

Precision: 1.0

Accuracy: 0.35714285714285715

[0 0 0 1 0 0 1 0 0 0 0 0 0 1]
Random Forest:

Recall: 0.18181818181818182

Precision: 0.6666666666666666

Accuracy: 0.2857142857142857

[0 0 0 0 0 0 0 0 0 1 0 0 0 0]
Gradient Boosting:

Recall: 0.09090909090909091

Precision: 1.0

Accuracy: 0.2857142857142857

[0 1 1 1 0 0 0 0 0 0 0 0 1 0]
K-Nearest Neighbors:

Recall: 0.18181818181818182

Precision: 0.5

Accuracy: 0.21428571428571427



In [36]:
def test_classifiers2(X_train, y_train, X_test, y_test):
    models = {

        'Gradient Boosting': GradientBoostingClassifier(),
        'K-Nearest Neighbors': KNeighborsClassifier()

    }

    results = {}

    for name, model in models.items():
        pipe = make_pipeline(model)
        pipe.fit(X_train, y_train)
        y_pred = pipe.predict(X_test)

        recall = recall_score(y_test, y_pred)
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)

        report = classification_report(y_test, y_pred)

        results[name] = {
            'accuracy': accuracy,
            'report': report,
            'precision' : precision
        }

        print(f"{name}:\n")
        print(f"Recall: {recall}\n")
        print(f"Precision: {precision}\n")
        print(f"Accuracy: {accuracy}\n")
        # table_results = pd.DataFrame({"Recall": recall,"Precision": precision, "Accuracy": accuracy})
        # print(f"Classification Report:\n{report}\n")
        # print(table_results)

    return results

In [37]:
results2 = test_classifiers2(X_train, y_train, X_test, y_test)

Gradient Boosting:

Recall: 0.5

Precision: 0.5714285714285714

Accuracy: 0.5

K-Nearest Neighbors:

Recall: 0.125

Precision: 1.0

Accuracy: 0.5



In [39]:
model_KNN = KNeighborsClassifier()

In [40]:
pipe_KNN = make_pipeline(model_KNN)
pipe_KNN.fit(X_train, y_train)
y_pred_KNN = pipe_KNN.predict(X_test)

recall_KNN = recall_score(y_test, y_pred_KNN)
accuracy_KNN = accuracy_score(y_test, y_pred_KNN)
precision_KNN = precision_score(y_test, y_pred_KNN)

In [41]:
display(recall_KNN)

0.3

In [42]:
display(accuracy_KNN)

0.5

In [43]:
display(precision_KNN)

1.0